language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
  - '6'
before_install:
  - npm i -g mocha
  - npm i -g typescript
  - npm i -g antlr4ts antltr4-cli
  - npm install
  - npm run-script build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
